[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'nodejs', 'libatomic_ops']

[phases.build]
cmds = ['composer install --no-dev', 'npm install && npm run build']

[start]
cmd = 'vendor/bin/heroku-php-apache2 public/'
