[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'nodejs']

[phases.install]
cmds = ['composer install --frozen-lockfile']

[phases.build]
cmds = ['npm install && npm run build', 'php artisan optimize']

[start]
cmd = 'vendor/bin/heroku-php-apache2 public/'
